#!/bin/bash

# From Mathias. Thank you!
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Apply the change
killall Dock
