#!/bin/bash

conf="$HOME/Library/Preferences/nsmb.conf"
synthetic_conf=/etc/synthetic.conf
host=capsule.galaxy.sc
user=thomas
shares='public private'
base_dir=/capsule
synthetic_dir=/System/Volumes/Data/capsule

mount_capsule() {
	local share password
	share=$1
	password=$2
	mount_smbfs "//${user}:${password}@${host}/${share}" "$base_dir/$share"
}

unmount_capsule() {
	local share
	share=$1
	umount "$base_dir/$share" >/dev/null
}

is_mounted() {
	local share
	share=$1
	# Not the most reliable way, but should work here
	mount | grep "$base_dir/$share" >/dev/null
}

is_empty() {
	local dir
	dir=$1
	[[ -z "$(ls -A "$dir")" ]]
}

setup_mount_target() {
	local share
	share=$1
	share_dir="$base_dir/$share"
	mkdir -p "$share_dir"
	if is_mounted "$share"; then
		unmount_capsule "$share"
	fi
	if ! is_empty "$share_dir"; then
		echo "ERROR: Even after attempting to unmount, $share_dir is empty"
		echo "ERROR: Failed to set up $share_dir"
		exit 1
	fi
	chown "$USER" "$share_dir"
	chmod u+rw "$share_dir"
}

create_conf() {
	cat >"$conf" <<-EOF
		[default]
		max_dirs_cached=0
	EOF
	chmod 400 "$conf"
}

get_password() {
	security find-generic-password -a "$user" -s capsule -w 2>/dev/null
}

set_password() {
	read -rsp "Samba password: " password
	security add-generic-password -a "$user" -s capsule -w "$password"
	unset password
}

setup_synthetic_links() {
	# New MacOS filesystems are read-only
	# /capsule has to be synthetically linked to work
	sudo mkdir "$synthetic_dir"
	sudo chown "$USER" "$synthetic_dir"
	sudo chmod u+rw "$synthetic_dir"
	sudo touch "$synthetic_conf"
	echo -e "capsule\t$synthetic_dir" | sudo tee "$synthetic_conf" >/dev/null
	sudo chown root:wheel "$synthetic_conf"
	sudo chmod 0644 "$synthetic_conf"
	sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t
}

# Create the config file if needed
if [[ ! -f "$conf" ]]; then
	create_conf
fi

# Set up synthetic hard links to root folder
if [[ ! -f "$synthetic_conf" ]]; then
	setup_synthetic_links
fi

# Set the password in the keychain
if [[ -z "$(get_password)" ]]; then
	set_password
fi

password="$(get_password)"

# Mount everything
for share in $shares; do
	# Set up the mount target dir for the share
	setup_mount_target "$share"

	# Mount the share
	if ! is_mounted "$share"; then
		mount_capsule "$share" "$password"
	fi

	echo "$base_dir/$share"
done

unset password
