#!/bin/bash

set -e

###########################################
# Prerequisites

# Exit if not on MacOS
if [[ "$(uname -s)" != Darwin ]]; then
	echo "This script should only be run on a MacOS system!"
	exit 1
fi

if [[ -z "$DOTDIR" ]] || [[ ! -d "$DOTDIR" ]]; then
	echo 'ERROR: Environment variable DOTDIR required, and must exist. Set up dot first!'
	exit 1
fi

current_hostname="$(scutil --get ComputerName)"
read -rp "Enter computer name (hostname) or leave blank to keep as-is [$current_hostname]: " hostname

###########################################
# Configure system

# Best reference ever:
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos

# Set computer name (as done via System Preferences → Sharing)
if [[ -n "$hostname" ]]; then
	sudo scutil --set ComputerName "$hostname"
	sudo scutil --set HostName "$hostname"
	sudo scutil --set LocalHostName "$hostname"
	sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$hostname"
fi

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Enable snap-to-grid for icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Disable auto-sleep
sudo pmset -a displaysleep 0 sleep 0 disksleep 0

# Disable creation of .DS_Store files on network/usb shares
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool TRUE

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen
# Top left
defaults write com.apple.dock wvous-tl-corner -int 4
defaults write com.apple.dock wvous-tl-modifier -int 0
# Top right
defaults write com.apple.dock wvous-tr-corner -int 0
defaults write com.apple.dock wvous-tr-modifier -int 0
# Bottom left
defaults write com.apple.dock wvous-bl-corner -int 2
defaults write com.apple.dock wvous-bl-modifier -int 0
# Bottom right
defaults write com.apple.dock wvous-br-corner -int 3
defaults write com.apple.dock wvous-br-modifier -int 0

# Require password immediately after sleep or screen saver begins
# These keys don't exist anymore. Do it manually in:
# 	System Preferences > Security & Privacy > General
# https://www.kolide.com/blog/macos-10-13-broke-screenlock-detection
#defaults write com.apple.screensaver askForPassword -int 1
#defaults write com.apple.screensaver askForPasswordDelay -int 0

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show the ~/Library folder
#chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library

# Restart apps to apply configuration
killall Dock
killall Finder

###########################################
# Packages

# Install brew
if ! command -v brew >/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install basic tools
brew install bash
brew install go
brew install gpg
brew install shellcheck
brew install shfmt
brew install step
brew install stats
brew install tmux
brew install vim

# gclip
go install golang.design/x/clipboard/cmd/gclip@latest

# Install applications
brew install --cask bitwarden
brew install --cask firefox
brew install --cask gimp
brew install --cask hiddenbar
brew install --cask libreoffice
brew install --cask lulu
brew install --cask keepingyouawake
brew install --cask openvpn-connect
brew install --cask protonvpn
brew install --cask rectangle
brew install --cask signal
brew install --cask vlc

###########################################
# Package configuration

# Set default shell to homebrew's newer bash
shell=/usr/local/bin/bash
if ! grep "$shell" /etc/shells >/dev/null 2>&1; then
	echo "$shell" | sudo tee -a /etc/shells >/dev/null
fi
if [[ "$SHELL" != "$shell" ]]; then
	chsh -s "$shell"
fi

# Set default shell in Terminal also
defaults write com.apple.Terminal Shell -string "$shell"

###########################################
# Galaxy

# Add galaxy CA
step certificate install --all "$DOTDIR/ssl/galaxy-ca.crt"

# TODO: Set up VPN
