#!/bin/bash

BINDIR='../scripts/bin'

if [[ -f "$HOME/.bash_profile" ]] && [[ ! -e "$HOME/.bash_profile.local" ]]; then
	mv "$HOME/.bash_profile" "$HOME/.bash_profile.local"
	echo "Existing .bash_profile was moved to .bash_profile.local"
fi

"$BINDIR/lns" "$(pwd)/.bash_profile" "$HOME/.bash_profile"
