#!/bin/bash

BINDIR='../scripts/bin'

bashprofile="$HOME/.bash_profile"
localprofile="$HOME/.bash_profile.local"

if [[ -f "$bashprofile" ]] && [[ ! -L "$bashprofile" ]] && [[ ! -e "$localprofile" ]]; then
	mv "$bashprofile" "$localprofile"
	echo "Existing .bash_profile was moved to .bash_profile.local"
fi

"$BINDIR/lns" "$(pwd)/.bash_profile" "$bashprofile"
"$BINDIR/lns" "$(pwd)/.bash_alias_completion" "$HOME/.bash_alias_completion"
